### ISSUE TITLE
calcGeomMeanLongSun issue.

### ISSUE THREAD

**Issue by kalimdor362** [rlxone/SolarNOAA#2]
Thanks for your code , it's helpful for me.
I found that in 1999 or 2000 the piece of the code falls in infinite loop and I made some modification.

    /// Calculate the Geometric Mean Longitude of the Sun
    ///
    /// - Parameter t: number of Julian centuries since J2000.0
    /// - Returns: the Geometric Mean Longitude of the Sun in degrees
    static func calcGeomMeanLongSun(_ t: Double) -> Double {
        var l0: Double = 0.0
        
        l0 = 280.46646 + t * (36000.76983 + 0.0003032 * t)
        
//        while (l0 <= 360) && (l0 >= 0) {
//            if l0 > 360 {
//                l0 = l0 - 360
//            }
//            if l0 < 0 {
//                l0 = l0 + 360
//            }
//        }
        while l0 > 360.0 {
            l0 = l0 - 360.0
        }
        while l0 < 0.0 {
            l0 = l0 + 360.0
        }
        
        return l0
    }

**Comment by rlxone** [comment]
Hi. Thank you. I've fixed those lines.
